-- Flyway V2: create auction_entries, sold, unsold tables

CREATE TABLE IF NOT EXISTS auction_entries (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  player_id BIGINT NOT NULL UNIQUE,
  order_index INT NOT NULL,
  category VARCHAR(200) NOT NULL,
  FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS sold (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  player_id BIGINT NOT NULL UNIQUE,
  team_id BIGINT NOT NULL,
  sold_price DOUBLE NOT NULL,
  sold_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE,
  FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS unsold (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  player_id BIGINT NOT NULL UNIQUE,
  unsold_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  requeue_count INT DEFAULT 0,
  FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE
);

